---
apiVersion: v1
kind: Secret
metadata:
  name: ovh-mks-exporter
type: Opaque
stringData:
  OVH_ENDPOINT: {{ .Values.ovh.endpoint }}
  OVH_APPLICATION_KEY: {{ .Values.ovh.application_key }}
  OVH_APPLICATION_SECRET: {{ .Values.ovh.application_secret }}
  OVH_CONSUMER_KEY: {{ .Values.ovh.consumer_key }}
  OVH_CLOUDPROJECT_SERVICENAME: {{ .Values.ovh.cloudproject_servicename }}
